-- ============================================================
-- College Discovery Platform — 60+ College Seed Data
-- Uses INSERT IGNORE with explicit IDs — safe to re-run
-- ============================================================

-- Clear and re-seed for clean data
INSERT IGNORE INTO colleges (id, name, location, fees, rating, placements, description, image, courses, facilities, reviews) VALUES

-- ── TIER 1: National Premier Institutions ────────────────────────────────────
(1,  'Indian Institute of Technology Bombay',
     'Mumbai, Maharashtra', 250000, 4.9, 2100000,
     'IIT Bombay is India''s premier engineering institution known for world-class research, exceptional alumni, and outstanding placement records with top global companies.',
     'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop',
     'B.Tech, M.Tech, MBA, Ph.D in Engineering & Science',
     'Central Library, Olympic Pool, Hostels, Research Labs, Cafeteria, Health Centre, Sports Complex',
     'Amazing campus and faculty. Placements are outstanding. Infrastructure is top-notch.'),

(2,  'Indian Institute of Technology Delhi',
     'New Delhi, Delhi', 230000, 4.8, 1950000,
     'IIT Delhi is a leading technical university in the capital, offering undergraduate and postgraduate programs in engineering and sciences with excellent research facilities.',
     'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&auto=format&fit=crop',
     'B.Tech, M.Tech, M.S, Ph.D in Engineering disciplines',
     'Central Library, Olympic Pool, Hostels, Research Centers, Medical Center, Auditorium',
     'Great research opportunities and excellent placement records. Faculty is very supportive.'),

(3,  'Indian Institute of Technology Madras',
     'Chennai, Tamil Nadu', 220000, 4.9, 2050000,
     'IIT Madras is India''s top-ranked engineering institution, set in a lush 600-acre campus with rich biodiversity, world-class research facilities and unmatched placements.',
     'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop',
     'B.Tech, M.Tech, MBA, M.Sc, Ph.D in Engineering & Humanities',
     'Forest Campus, Sports Complex, Hostels, Research Parks, Library, Hospital, Food Courts',
     'Stunning campus. Research quality and placements are second to none in India.'),

(4,  'BITS Pilani',
     'Pilani, Rajasthan', 450000, 4.7, 1600000,
     'BITS Pilani is a premier private engineering institute with flexible academics, Practice School program, and strong MNC connections across technology sectors.',
     'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800&auto=format&fit=crop',
     'B.E, M.E, M.Phil, Ph.D in Engineering and Sciences',
     'Sports Ground, Labs, Library, Hostels, Food Court, Cultural Center, Medical Facility',
     'Excellent curriculum and industry exposure. Campus life is vibrant and engaging.'),

(5,  'NIT Trichy',
     'Tiruchirappalli, Tamil Nadu', 145000, 4.6, 1200000,
     'NIT Trichy is consistently among India''s top NITs, offering excellent technical education with strong industry partnerships and research programs across all branches.',
     'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&auto=format&fit=crop',
     'B.Tech, M.Tech, MBA, MCA, Ph.D programs',
     'Gymnasium, Swimming Pool, Hostels, Library, Health Center, Auditorium, Sports Ground',
     'Great college with awesome faculty. Placements are very good across all branches.'),

(6,  'VIT University Vellore',
     'Vellore, Tamil Nadu', 185000, 4.4, 980000,
     'VIT Vellore is one of India''s top private universities, recognized for quality education, international collaborations, and strong placement records with Fortune 500 companies.',
     'https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=800&auto=format&fit=crop',
     'B.Tech, M.Tech, MBA, MCA, Ph.D in 40+ specializations',
     'Olympic Pool, Indoor Stadium, Hostels, Library, Labs, Shopping Complex, Hospital',
     'Excellent infrastructure and international exposure. Very student-friendly environment.'),

(7,  'Delhi Technological University',
     'New Delhi, Delhi', 165000, 4.3, 1050000,
     'DTU is a leading government technical university in Delhi with strong emphasis on research, innovation, and industry collaboration across 13 diverse engineering branches.',
     'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&auto=format&fit=crop',
     'B.Tech, M.Tech, MBA, Ph.D across 13 engineering branches',
     'Library, Sports Complex, Labs, Hostels, Cafeteria, Auditorium, Innovation Center',
     'Good college with decent placements. Faculty is experienced and supportive.'),

(8,  'Indian Institute of Management Bangalore',
     'Bengaluru, Karnataka', 2400000, 4.9, 3200000,
     'IIM Bangalore is India''s top business school renowned for its rigorous MBA program, world-class faculty, case-study pedagogy, and exceptional global alumni network.',
     'https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=800&auto=format&fit=crop',
     'MBA, Executive MBA, Ph.D in Management programs',
     'Library, Hostels, Sports Facilities, Research Centers, Auditorium, Cafeteria, Case Study Rooms',
     'Best MBA college in India. Network and learning experience are truly world-class.'),

(9,  'Manipal Institute of Technology',
     'Manipal, Karnataka', 410000, 4.5, 1100000,
     'MIT Manipal is a prestigious private engineering college under Manipal University, offering diverse programs with excellent global exposure and strong industry collaborations.',
     'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&auto=format&fit=crop',
     'B.Tech, M.Tech, MBA, MCA, Ph.D in various disciplines',
     'Beach Access, Sports Ground, Hostels, Library, Research Labs, Hospital, Food Courts',
     'Beautiful campus and great environment. Excellent international opportunities for students.'),

(10, 'Anna University',
     'Chennai, Tamil Nadu', 80000, 4.5, 750000,
     'Anna University is Tamil Nadu''s premier state technical university, functioning as an affiliating university for 500+ engineering colleges while maintaining outstanding research standards.',
     'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech, MBA, MCA, Ph.D programs',
     'Campus Library, Research Labs, Hostels, Sports Complex, Auditorium, Seminar Halls, Cafeteria',
     'Excellent government university with low fees. Great for research and academics.'),

(11, 'Amrita Vishwa Vidyapeetham',
     'Coimbatore, Tamil Nadu', 175000, 4.5, 900000,
     'Amrita is a deemed-to-be-university with campuses across India, known for research excellence, spiritual environment, NIRF top rankings, and strong industry-academia partnerships.',
     'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop',
     'B.Tech, M.Tech, BBA, MBA, B.Sc, M.Sc, Ph.D across campuses',
     'Research Labs, Library, Hostels, Sports Complex, Hospital, Meditation Center, Cafeteria',
     'Great research culture and spiritual environment. Excellent faculty and placements.'),

(12, 'SSN College of Engineering',
     'Chennai, Tamil Nadu', 160000, 4.4, 850000,
     'SSN College of Engineering is one of Tamil Nadu''s top autonomous engineering colleges, known for academic excellence, strong alumni base, and consistent placement performance.',
     'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech in CSE, ECE, Mechanical, Civil, IT and more',
     'Library, Seminar Halls, Labs, Hostels, Sports Ground, Canteen, Innovation Hub',
     'One of the best private engineering colleges in Chennai. Great faculty and placements.'),

(13, 'PSG College of Technology',
     'Coimbatore, Tamil Nadu', 130000, 4.5, 820000,
     'PSG College of Technology is a premier autonomous engineering institution in Coimbatore, known for its strong industry connections, experienced faculty, and excellent placements in IT and core sectors.',
     'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech, MBA, MCA in CSE, ECE, Mech, Civil, IT, AI & DS',
     'Central Library, Hostels, Sports Complex, Labs, Canteen, Auditorium, Health Center',
     'Excellent autonomous college with strong industry ties. Great placements in Coimbatore companies.'),

(14, 'Kumaraguru College of Technology',
     'Coimbatore, Tamil Nadu', 120000, 4.3, 720000,
     'KCT is a leading autonomous engineering college in Coimbatore offering quality technical education with entrepreneurship focus, strong industry linkages, and consistent placement records.',
     'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech in CSE, ECE, Mechanical, Civil, IT, AI & ML',
     'Library, Sports Ground, Hostels, Labs, Canteen, Auditorium, Entrepreneurship Center',
     'Good autonomous college with entrepreneurship culture. Solid placements and active college life.'),

(15, 'Coimbatore Institute of Technology',
     'Coimbatore, Tamil Nadu', 110000, 4.2, 680000,
     'CIT Coimbatore is one of the oldest and most reputed government-aided engineering colleges in Tamil Nadu, offering quality education with affordable fees and good placement opportunities.',
     'https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech in CSE, ECE, EEE, Mechanical, Civil, IT',
     'Library, Labs, Sports Ground, Canteen, Auditorium, Seminar Halls, Workshop',
     'Great government-aided college with affordable fees. Good faculty and placement track record.'),

(16, 'Karpagam Institute of Technology',
     'Coimbatore, Tamil Nadu', 95000, 4.2, 620000,
     'Karpagam Institute of Technology (KIT) is a reputed private engineering college in Coimbatore offering quality education in engineering and technology with strong focus on IT placements and skill development.',
     'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop',
     'B.E, B.Tech in CSE, AI & DS, ECE, Mechanical, Civil, EEE, IT, AI & ML',
     'Hostel, Central Library, Computer Labs, Sports Facility, Transport, Cafeteria, Seminar Halls',
     'Good college with improving placements. Strong focus on skill development and certifications.'),

(17, 'Karpagam College of Engineering',
     'Coimbatore, Tamil Nadu', 100000, 4.1, 600000,
     'Karpagam College of Engineering is a well-established private engineering college under Karpagam Academy of Higher Education, offering comprehensive technical programs with industry-oriented curriculum.',
     'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E in CSE, ECE, Mechanical, Civil, EEE, IT, AI & DS',
     'Library, Labs, Hostel, Sports Ground, Transport, Canteen, Workshop Facilities',
     'Decent engineering college with good infrastructure. Faculty is supportive and approachable.'),

(18, 'Karpagam Academy of Higher Education',
     'Coimbatore, Tamil Nadu', 85000, 4.0, 550000,
     'Karpagam Academy of Higher Education is a deemed university in Coimbatore offering diverse undergraduate and postgraduate programs in arts, science, engineering and management.',
     'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800&auto=format&fit=crop',
     'B.E, B.Tech, BBA, B.Sc, MBA, M.Sc, M.Tech, Ph.D in multiple disciplines',
     'Library, Labs, Hostel, Sports Ground, Medical Center, Transport, Canteen',
     'Good deemed university offering diverse programs. Nice campus environment and facilities.'),

(19, 'Sri Krishna College of Engineering and Technology',
     'Coimbatore, Tamil Nadu', 115000, 4.2, 660000,
     'SKCET is a prominent autonomous engineering college in Coimbatore known for its quality technical education, active placement cell, and strong connections with IT and manufacturing industries.',
     'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech in CSE, ECE, Mechanical, Civil, IT, AI & DS, CSBS',
     'Library, Labs, Hostel, Sports Complex, Canteen, Auditorium, Seminar Halls, Transport',
     'Good college with active placement cell. Strong in IT and core engineering placements.'),

(20, 'SNS College of Technology',
     'Coimbatore, Tamil Nadu', 105000, 4.1, 590000,
     'SNS College of Technology is part of the SNS Institutions group, offering quality engineering education with modern infrastructure, entrepreneurship programs, and industry-oriented curriculum in Coimbatore.',
     'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech in CSE, ECE, Mechanical, Civil, IT, AI & ML',
     'Library, Labs, Hostel, Sports Ground, Transport, Canteen, Innovation Center, Auditorium',
     'Good college with entrepreneurship focus. SNS group provides good infrastructure and facilities.'),

(21, 'Bannari Amman Institute of Technology',
     'Erode, Tamil Nadu', 115000, 4.3, 700000,
     'BIT Sathyamangalam is a well-reputed autonomous engineering college in Erode district, known for excellent academics, strong placement records, and disciplined campus culture.',
     'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech in CSE, ECE, EEE, Mechanical, Civil, IT, AI & DS',
     'Library, Labs, Hostel, Sports Complex, Canteen, Auditorium, Workshop, Health Center',
     'Excellent discipline and academics. Strong placements especially in core engineering and IT.'),

(22, 'Dr NGP Institute of Technology',
     'Coimbatore, Tamil Nadu', 110000, 4.1, 610000,
     'Dr NGP Institute of Technology is a reputed engineering college in Coimbatore offering quality technical education with strong focus on research, innovation, and industry-ready skills.',
     'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech in CSE, ECE, Mechanical, Civil, IT, AI & DS',
     'Library, Labs, Hostel, Sports Ground, Canteen, Seminar Halls, Transport',
     'Decent college with good faculty. Improving placements year over year in IT sector.'),

(23, 'Sri Ramakrishna Engineering College',
     'Coimbatore, Tamil Nadu', 120000, 4.3, 710000,
     'SREC Coimbatore is a top-ranked autonomous engineering college known for its academic excellence, strong industry collaboration, active R&D culture, and consistent placement performance.',
     'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech in CSE, ECE, EEE, Mechanical, Civil, IT, CSBS',
     'Library, Labs, Hostel, Sports Complex, Canteen, Innovation Center, Auditorium, Research Cells',
     'Excellent autonomous college. Strong academics and good placement record in Coimbatore.'),

(24, 'Government College of Technology',
     'Coimbatore, Tamil Nadu', 50000, 4.4, 780000,
     'GCT Coimbatore is one of Tamil Nadu''s oldest and most prestigious government engineering colleges, offering world-class technical education at highly affordable fees with strong placement outcomes.',
     'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech in CSE, ECE, EEE, Mechanical, Civil, Textile, Fashion',
     'Library, Research Labs, Hostel, Sports Complex, Canteen, Workshop, Auditorium',
     'Best government engineering college in Coimbatore. Excellent value for money education.'),

(25, 'Kongu Engineering College',
     'Erode, Tamil Nadu', 105000, 4.3, 690000,
     'Kongu Engineering College is a prestigious autonomous institution in Erode known for its excellent academic standards, strong alumni network, and good placements in IT and manufacturing sectors.',
     'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech in CSE, ECE, EEE, Mechanical, Civil, IT, AI & DS',
     'Library, Labs, Hostel, Sports Complex, Canteen, Auditorium, Workshop, Transport',
     'Very good autonomous college in Erode. Strong in core engineering and IT placements.'),

(26, 'Hindusthan College of Engineering and Technology',
     'Coimbatore, Tamil Nadu', 100000, 4.0, 560000,
     'HCET Coimbatore is a well-established private engineering college offering comprehensive technical programs with modern facilities, active placement cell, and industry-oriented training.',
     'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech in CSE, ECE, Mechanical, Civil, IT, EEE',
     'Library, Labs, Hostel, Sports Ground, Canteen, Auditorium, Transport Facility',
     'Good college with decent placements. Improving year over year in IT and core sectors.'),

(27, 'Rathinam Technical Campus',
     'Coimbatore, Tamil Nadu', 90000, 3.9, 500000,
     'Rathinam Technical Campus is a growing private engineering college in Coimbatore with focus on practical skill development, industry training programs, and improving placement outcomes.',
     'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop',
     'B.E, B.Tech in CSE, ECE, Mechanical, Civil, IT, AI & DS, EEE',
     'Library, Labs, Hostel, Sports Ground, Canteen, Transport, Seminar Halls',
     'Affordable college with practical focus. Good for students seeking skill-based education.'),

(28, 'Thiagarajar College of Engineering',
     'Madurai, Tamil Nadu', 125000, 4.4, 800000,
     'TCE Madurai is a prestigious autonomous engineering college with over 60 years of excellence, known for strong technical education, active research, and excellent placement records across all branches.',
     'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech in CSE, ECE, EEE, Mechanical, Civil, IT, AI & DS',
     'Library, Research Labs, Hostel, Sports Complex, Canteen, Auditorium, Workshop, Health Center',
     'One of Madurai''s best engineering colleges. Excellent academics and placement culture.'),

(29, 'Velammal Engineering College',
     'Chennai, Tamil Nadu', 130000, 4.2, 720000,
     'Velammal Engineering College is a well-known private engineering institution in Chennai offering quality technical education with good infrastructure, strong placement cell, and industry connections.',
     'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech in CSE, ECE, Mechanical, Civil, IT, EEE, AI & DS',
     'Library, Labs, Hostel, Sports Complex, Canteen, Auditorium, Transport, Health Center',
     'Good private college in Chennai. Strong placement record and decent campus facilities.'),

(30, 'SRM Easwari Engineering College',
     'Chennai, Tamil Nadu', 125000, 4.2, 730000,
     'SRM Easwari Engineering College is a reputed autonomous engineering college in Chennai under SRM Group, known for its strong academic standards, industry partnerships, and placement performance.',
     'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech in CSE, ECE, Mechanical, Civil, IT, EEE, AI & DS',
     'Library, Labs, Hostel, Sports Ground, Canteen, Auditorium, Innovation Hub, Transport',
     'Good SRM group college with strong autonomous curriculum. Decent placements in Chennai.'),

(31, 'Sairam Engineering College',
     'Chennai, Tamil Nadu', 120000, 4.1, 680000,
     'Sairam Engineering College is a growing private engineering institution in Chennai with modern infrastructure, improving placement records, and active student development programs.',
     'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech in CSE, ECE, Mechanical, Civil, IT, EEE, CSBS',
     'Library, Labs, Hostel, Sports Complex, Canteen, Auditorium, Health Center, Transport',
     'Good college with modern infrastructure. Placement improving every year in IT sector.'),

(32, 'Panimalar Engineering College',
     'Chennai, Tamil Nadu', 115000, 4.1, 650000,
     'Panimalar Engineering College is a well-established private engineering college in Chennai offering quality technical education with active industry partnerships and student placement support.',
     'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech in CSE, ECE, Mechanical, Civil, IT, EEE, AI & DS',
     'Library, Labs, Hostel, Sports Ground, Canteen, Auditorium, Transport, Seminar Halls',
     'Decent private college in Chennai. Good for students from nearby localities.'),

(33, 'Saveetha Engineering College',
     'Chennai, Tamil Nadu', 120000, 4.0, 620000,
     'Saveetha Engineering College is part of the Saveetha Institutions group in Chennai, offering engineering education with focus on innovation, research, and industry-ready skill development.',
     'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech in CSE, ECE, Mechanical, Civil, IT, EEE, AI & ML',
     'Library, Labs, Hostel, Sports Complex, Canteen, Auditorium, Transport, Research Center',
     'Good Saveetha group college. Active research culture and decent placement support.'),

(34, 'Chennai Institute of Technology',
     'Chennai, Tamil Nadu', 125000, 4.2, 700000,
     'Chennai Institute of Technology is a reputed autonomous engineering college in Chennai known for strong technical programs, modern infrastructure, active placement training, and industry collaboration.',
     'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech in CSE, ECE, Mechanical, Civil, IT, EEE, AI & DS, CSBS',
     'Library, Labs, Hostel, Sports Complex, Canteen, Auditorium, Innovation Hub, Transport',
     'Good autonomous college in Chennai. Strong curriculum and active placement activities.'),

(35, 'RMK Engineering College',
     'Chennai, Tamil Nadu', 110000, 4.0, 600000,
     'RMK Engineering College is a well-known private engineering institution in Kavaraipettai, Chennai, offering quality technical education with good campus facilities and placement support.',
     'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech in CSE, ECE, Mechanical, Civil, IT, EEE',
     'Library, Labs, Hostel, Sports Ground, Canteen, Auditorium, Transport, Workshop',
     'Good private college with decent infrastructure. Placement support is actively provided.'),

(36, 'St Joseph College of Engineering',
     'Chennai, Tamil Nadu', 135000, 4.3, 760000,
     'St Joseph College of Engineering is a reputed Catholic minority institution in Chennai offering excellent engineering education with strong values, active placement cell, and industry connections.',
     'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech in CSE, ECE, Mechanical, Civil, IT, EEE, AI & DS',
     'Chapel, Library, Labs, Hostel, Sports Complex, Canteen, Auditorium, Transport',
     'Excellent minority institution. Strong values, good academics and placement performance.'),

(37, 'VIT Chennai',
     'Chennai, Tamil Nadu', 195000, 4.3, 950000,
     'VIT Chennai campus offers the same quality education as VIT Vellore in an urban Chennai setting with excellent industry exposure, modern facilities, and strong placement support from top companies.',
     'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop',
     'B.Tech, M.Tech, MBA in CSE, ECE, Mechanical, Civil, IT, AI & DS, CSBS',
     'Library, Labs, Hostel, Sports Complex, Canteen, Auditorium, Innovation Hub, Transport',
     'Good VIT campus in Chennai. Excellent placements and modern infrastructure.'),

(38, 'Loyola College',
     'Chennai, Tamil Nadu', 45000, 4.5, 650000,
     'Loyola College Chennai is one of India''s most prestigious arts and science colleges, a Jesuit institution known for academic excellence, strong humanities programs, and exceptional alumni.',
     'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800&auto=format&fit=crop',
     'B.A, B.Sc, B.Com, BBA, B.C.A, M.A, M.Sc, M.Com, MCA, Ph.D',
     'Chapel, Library, Labs, Sports Ground, Canteen, Auditorium, Research Center, NCC Wing',
     'One of India''s best arts colleges. Excellent academics, strong alumni and great placement support.'),

(39, 'Madras Christian College',
     'Chennai, Tamil Nadu', 40000, 4.5, 600000,
     'MCC Chennai is a historic autonomous arts and science college established in 1837, offering excellent liberal education, strong research culture, and a diverse learning environment in the heart of Chennai.',
     'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&auto=format&fit=crop',
     'B.A, B.Sc, B.Com, BBA, B.C.A, M.A, M.Sc, M.Com, Ph.D programs',
     'Historic Library, Labs, Sports Complex, Canteen, Auditorium, NCC Wing, Chapel',
     'One of India''s oldest colleges. Excellent academics and a truly enriching campus experience.'),

(40, 'PSG College of Arts and Science',
     'Coimbatore, Tamil Nadu', 55000, 4.3, 580000,
     'PSG College of Arts and Science is a reputed autonomous college in Coimbatore offering a wide range of arts, science, and commerce programs with strong placement support and academic excellence.',
     'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&auto=format&fit=crop',
     'B.A, B.Sc, B.Com, BBA, B.C.A, M.A, M.Sc, M.Com, MCA, MBA programs',
     'Library, Labs, Sports Ground, Canteen, Auditorium, Transport, NCC Wing',
     'Good autonomous arts and science college in Coimbatore with strong alumni network.'),

(41, 'Sri Ramakrishna Arts and Science College',
     'Coimbatore, Tamil Nadu', 50000, 4.2, 520000,
     'SRASC Coimbatore is a well-reputed autonomous arts and science college offering quality education in science, commerce, and humanities with strong placement support and industry exposure.',
     'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop',
     'B.A, B.Sc, B.Com, BBA, B.C.A, M.A, M.Sc, M.Com, MCA programs',
     'Library, Labs, Sports Ground, Canteen, Auditorium, Transport, Seminar Halls',
     'Good arts and science college. Strong academics and supportive faculty environment.'),

(42, 'KG College of Arts and Science',
     'Coimbatore, Tamil Nadu', 48000, 4.0, 480000,
     'KG College of Arts and Science is a growing private college in Coimbatore offering diverse programs in arts, science, and commerce with focus on student development and placement support.',
     'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop',
     'B.A, B.Sc, B.Com, BBA, B.C.A, M.A, M.Sc, M.Com programs',
     'Library, Labs, Sports Ground, Canteen, Auditorium, Transport',
     'Good private arts college in Coimbatore. Affordable fees and supportive environment.'),

(43, 'Dr GRD College of Science',
     'Coimbatore, Tamil Nadu', 52000, 4.1, 510000,
     'Dr GRD College of Science in Coimbatore offers quality science and commerce programs with modern laboratories, experienced faculty, and active career guidance for students.',
     'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800&auto=format&fit=crop',
     'B.Sc, B.Com, BBA, B.C.A, M.Sc, M.Com, MBA, MCA programs',
     'Library, Labs, Sports Ground, Canteen, Auditorium, Transport, Seminar Halls',
     'Good science college in Coimbatore. Affordable and student-friendly environment.'),

(44, 'Jadavpur University',
     'Kolkata, West Bengal', 25000, 4.6, 900000,
     'Jadavpur University is a premier public university in Eastern India, celebrated for its strong engineering, sciences, and humanities departments offering quality education at very low cost.',
     'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&auto=format&fit=crop',
     'B.Tech, B.E, M.Tech, M.E, MBA, MA, Ph.D programs',
     'Library, Sports Ground, Hostels, Labs, Auditorium, Canteen, Research Centers',
     'Excellent government college with very low fees. Strong culture and good CS/EE placements.'),

(45, 'SRM Institute of Science and Technology',
     'Chennai, Tamil Nadu', 195000, 4.2, 850000,
     'SRM Institute is a top-ranked private university known for modern infrastructure, wide range of programs across all disciplines, and active placement cell connecting students to global companies.',
     'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&auto=format&fit=crop',
     'B.Tech, M.Tech, BBA, MBA, MBBS, Ph.D in 60+ programs',
     'Hospital, Sports Complex, Hostels, Library, Labs, Shopping Mall, Bank, Transport',
     'Great infrastructure and active placement. The SRM brand opens many industry doors.'),

(46, 'Amity University',
     'Noida, Uttar Pradesh', 250000, 4.0, 750000,
     'Amity University is one of India''s largest private universities offering diverse programs with strong industry connections, international collaborations, and vibrant campus life.',
     'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop',
     'B.Tech, BBA, B.Com, MBA, LLB, MBBS, Ph.D in 150+ programs',
     'Sports Complex, Hostels, Hospital, Library, Labs, Food Court, Bank, Transport',
     'Good university with excellent facilities. Campus is very large and well-maintained.'),

(47, 'Christ University',
     'Bengaluru, Karnataka', 185000, 4.4, 700000,
     'Christ University Bangalore is a prestigious deemed university known for holistic education, discipline, strong arts, commerce, and management programs in a well-maintained campus.',
     'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop',
     'BBA, B.Com, BA, B.Sc, MBA, MA, M.Com, Ph.D programs',
     'Chapel, Sports Complex, Library, Hostels, Labs, Cafeteria, Auditorium',
     'Excellent for commerce and arts. Great faculty and strong discipline culture on campus.'),

(48, 'Symbiosis International University',
     'Pune, Maharashtra', 320000, 4.3, 880000,
     'Symbiosis International University has a global outlook offering interdisciplinary programs in law, management, technology, media, and social sciences with excellent industry exposure.',
     'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800&auto=format&fit=crop',
     'BBA, B.Com, B.Tech, LLB, MBA, MA, Ph.D in diverse programs',
     'Sports Complex, Hostels, Library, Labs, Food Court, Cultural Center, Innovation Hub',
     'Great for management programs. International exposure is excellent. Beautiful campus.'),

(49, 'Jain University',
     'Bengaluru, Karnataka', 200000, 4.2, 780000,
     'Jain University is a well-known deemed university in Bengaluru offering diverse programs across engineering, management, arts, and sciences with strong sports culture and placement support.',
     'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&auto=format&fit=crop',
     'B.Tech, BBA, B.Com, BA, MBA, M.Tech, Ph.D in various disciplines',
     'Sports Complex, Hostels, Library, Labs, Cafeteria, Auditorium, Innovation Center',
     'Good deemed university in Bangalore. Known for sports excellence and diverse programs.'),

(50, 'Pune Institute of Computer Technology',
     'Pune, Maharashtra', 120000, 4.3, 800000,
     'PICT is a premier autonomous engineering college in Pune with a strong focus on computer science, vibrant coding culture, excellent placements, and some of the best CS faculty in Maharashtra.',
     'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&auto=format&fit=crop',
     'B.E in Computer, IT, ENTC, Mechanical, MCA, ME programs',
     'Computer Labs, Library, Canteen, Sports Ground, Auditorium, Seminar Halls',
     'One of the best CS colleges in Pune. Great coding culture and excellent placements.'),

(51, 'Coimbatore Institute of Engineering and Technology',
     'Coimbatore, Tamil Nadu', 105000, 4.0, 580000,
     'CIET Coimbatore is a steadily growing engineering college offering technical education with a practical approach, industry-oriented curriculum, and consistent placement support for students.',
     'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop',
     'B.E, B.Tech in CSE, ECE, Mechanical, Civil, EEE, IT',
     'Library, Labs, Hostel, Sports Ground, Canteen, Workshop, Transport',
     'Good college for students seeking affordable engineering education in Coimbatore.'),

(52, 'Sri Eshwar College of Engineering',
     'Coimbatore, Tamil Nadu', 108000, 4.2, 640000,
     'Sri Eshwar College of Engineering is a well-known autonomous institution in Coimbatore known for strong academics, active research culture, entrepreneurship programs, and good IT placements.',
     'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech in CSE, ECE, Mechanical, Civil, IT, AI & DS, EEE',
     'Library, Labs, Hostel, Sports Complex, Canteen, Entrepreneurship Center, Transport',
     'Good autonomous college in Coimbatore. Active research and entrepreneurship culture.'),

(53, 'Nandha Engineering College',
     'Erode, Tamil Nadu', 95000, 4.0, 560000,
     'Nandha Engineering College is a reputed private engineering institution in Erode offering quality technical education with modern labs, experienced faculty, and good placement support.',
     'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech in CSE, ECE, Mechanical, Civil, EEE, IT',
     'Library, Labs, Hostel, Sports Ground, Canteen, Auditorium, Workshop, Transport',
     'Good engineering college in Erode. Affordable fees and practical-oriented education.'),

(54, 'Karunya Institute of Technology and Sciences',
     'Coimbatore, Tamil Nadu', 145000, 4.3, 730000,
     'Karunya Institute is a Christian deemed university in Coimbatore with strong emphasis on values, quality technical education, research culture, and good placements in IT and core sectors.',
     'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.Tech, BBA, MBA, B.Sc, Ph.D programs',
     'Chapel, Library, Labs, Hostel, Sports Complex, Canteen, Research Center, Auditorium',
     'Good Christian institution with values-based education. Decent placements and facilities.'),

(55, 'Avinashilingam Institute for Home Science',
     'Coimbatore, Tamil Nadu', 65000, 4.2, 520000,
     'Avinashilingam Deemed University is a women''s university in Coimbatore offering programs in home science, education, engineering, and management with a strong focus on women empowerment.',
     'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&auto=format&fit=crop',
     'B.Sc, B.Ed, B.Tech, BBA, MBA, M.Sc, M.Ed, Ph.D programs',
     'Library, Labs, Hostel, Sports Ground, Canteen, Auditorium, Research Center',
     'Excellent women''s university in Coimbatore. Strong focus on women empowerment and education.'),

(56, 'Park College of Engineering and Technology',
     'Coimbatore, Tamil Nadu', 100000, 3.9, 530000,
     'Park College of Engineering and Technology is a private engineering college in Coimbatore offering technical programs with affordable fees, practical training, and industry-oriented curriculum.',
     'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop',
     'B.E, B.Tech in CSE, ECE, Mechanical, Civil, EEE, IT',
     'Library, Labs, Hostel, Sports Ground, Canteen, Workshop, Transport',
     'Affordable engineering college in Coimbatore. Good for students on a budget.'),

(57, 'KPR Institute of Engineering and Technology',
     'Coimbatore, Tamil Nadu', 112000, 4.2, 670000,
     'KPR Institute of Engineering and Technology is a well-known autonomous engineering college in Coimbatore with good infrastructure, active placement cell, and industry-oriented curriculum.',
     'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech in CSE, ECE, Mechanical, Civil, IT, EEE, AI & DS',
     'Library, Labs, Hostel, Sports Complex, Canteen, Auditorium, Transport, Health Center',
     'Good autonomous college. Strong placement support and modern infrastructure.'),

(58, 'Vel Tech Rangarajan Dr Sagunthala University',
     'Chennai, Tamil Nadu', 150000, 4.1, 720000,
     'Vel Tech is a deemed university in Chennai with multiple campuses offering engineering and technology programs with strong placement support, industry connections, and diverse specializations.',
     'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800&auto=format&fit=crop',
     'B.Tech, M.Tech, MBA, MCA, Ph.D in CSE, ECE, Mechanical, Civil, IT, AI & DS',
     'Library, Labs, Hostel, Sports Complex, Canteen, Auditorium, Innovation Hub',
     'Good deemed university in Chennai. Strong industry connections and placement support.'),

(59, 'Bannari Amman Institute of Technology Sathyamangalam',
     'Erode, Tamil Nadu', 118000, 4.3, 700000,
     'BIT Sathyamangalam is a top autonomous engineering institution in Erode with excellent academics, experienced faculty, active industry linkages, and strong placement support in IT and manufacturing.',
     'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech in CSE, ECE, EEE, Mechanical, Civil, IT, AI & DS',
     'Library, Labs, Hostel, Sports Complex, Canteen, Workshop, Auditorium, Health Center',
     'One of Erode''s best engineering colleges. Strong in both IT and core engineering placements.'),

(60, 'Maharaja Engineering College',
     'Erode, Tamil Nadu', 92000, 3.9, 510000,
     'Maharaja Engineering College is a growing private engineering institution in Erode district offering quality technical education with affordable fees, modern facilities, and placement support.',
     'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&auto=format&fit=crop',
     'B.E, B.Tech in CSE, ECE, Mechanical, Civil, EEE, IT',
     'Library, Labs, Hostel, Sports Ground, Canteen, Workshop, Transport',
     'Affordable engineering college in Erode. Good for students from semi-urban backgrounds.'),

(61, 'Mepco Schlenk Engineering College',
     'Virudhunagar, Tamil Nadu', 110000, 4.3, 710000,
     'Mepco Schlenk Engineering College is a premier autonomous engineering institution in Southern Tamil Nadu known for excellent academics, research culture, and strong placement records.',
     'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech in CSE, ECE, EEE, Mechanical, Civil, IT, AI & DS',
     'Library, Labs, Hostel, Sports Complex, Canteen, Auditorium, Workshop, Research Center',
     'Excellent autonomous college in Southern TN. Strong academics and good placements.'),

(62, 'National Engineering College',
     'Kovilpatti, Tamil Nadu', 105000, 4.2, 680000,
     'National Engineering College Kovilpatti is a reputed autonomous engineering institution with strong technical programs, experienced faculty, active industry connections, and good placement records.',
     'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop',
     'B.E, B.Tech, M.E, M.Tech in CSE, ECE, EEE, Mechanical, Civil, IT',
     'Library, Labs, Hostel, Sports Complex, Canteen, Auditorium, Workshop',
     'Good autonomous college in Southern TN. Strong in both core and IT placements.');
